# Generated by Django 6.0.3 on 2026-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superAdminID', models.AutoField(primary_key=True, serialize=False)),
                ('superAdminName', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contactNumber', models.CharField(max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
    ]
