# Generated by Django 6.0.3 on 2026-03-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0006_event_declinereason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('publicUserID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('registrationDate', models.DateTimeField(auto_now_add=True)),
                ('isRegistered', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=300)),
                ('barangay', models.CharField(max_length=100)),
                ('report', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submittedDate', models.DateTimeField(auto_now_add=True)),
                ('validatedBy', models.IntegerField(blank=True, null=True)),
                ('validatedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('responded', 'Responded')], default='pending', max_length=20)),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('adminResponse', models.TextField(blank=True, null=True)),
                ('respondedDate', models.DateTimeField(blank=True, null=True)),
                ('assignedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='adminpanel.admin')),
                ('publicUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='publicpanel.publicuser')),
            ],
            options={
                'ordering': ['-submittedDate'],
            },
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='report_media/')),
                ('mediaType', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='publicpanel.report')),
            ],
        ),
    ]
