# Generated by Django 6.0.3 on 2026-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='adminResponse',
        ),
        migrations.AddField(
            model_name='report',
            name='adminResponses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='isResolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='resolvedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
