# Generated by Django 6.0.3 on 2026-03-31 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpanel', '0002_remove_report_adminresponse_report_adminresponses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotlineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(default='📞', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotlines', to='publicpanel.hotlinecategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
