# Generated by Django 6.0.3 on 2026-04-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpanel', '0003_hotlinecategory_hotline'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuser',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
