# Generated by Django 6.0.3 on 2026-04-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpanel', '0004_publicuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='public_profiles/'),
        ),
    ]
