# Generated by Django 5.2.6 on 2026-04-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpanel', '0005_alter_publicuser_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
