# Generated by Django 6.0.3 on 2026-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='isPinned',
            field=models.BooleanField(default=False),
        ),
    ]
