# Generated by Django 6.0.3 on 2026-03-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_announcement_ispinned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('eventDate', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('posterPath', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('approvedBy', models.IntegerField(blank=True, null=True)),
                ('approvedDate', models.DateTimeField(blank=True, null=True)),
                ('isApproved', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='adminpanel.admin')),
            ],
            options={
                'ordering': ['-createdDate'],
            },
        ),
    ]
