# Generated by Django 6.0.3 on 2026-03-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_announcementmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='declineReason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
