# Generated by Django 6.0.3 on 2026-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_event_declinereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='admin_profiles/'),
        ),
    ]
