# Generated by Django 5.2.6 on 2026-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_admin_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
